name: GitHub Actions Gcloud Function Deploy
run-name: ${{ github.actor }} is deploying Gcloud Function 🚀
on:
  push:
    branches:
      - main
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: 'Enable Initial Services'
      id: 'init'
      env:
        INIT_FLAG: ${{ vars.INIT_FLAG }}
      if: ${{ env.INIT_FLAG == '' }} 
      run: echo "INIT_FLAG=1" >> $GITHUB_ENV

    - name: 'INIT_FLAG echo'
      id: 'init-echo'
      env:
        INIT_FLAG: ${{ vars.INIT_FLAG }}
      run: echo $INIT_FLAG

