name: GitHub Actions Gcloud Function Deploy
run-name: ${{ github.actor }} is deploying Gcloud Function 🚀
on:
  push:
    branches:
      - main
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: 'tsc-build'
      name: 'Setup code env'
      run: | 
        npm i
        npm run build

    #https://github.com/google-github-actions/auth
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Deploy a Cloud Function
      id: deploy-function
      uses: google-github-actions/deploy-cloud-functions@v0.1.0
      with:
        name: my-function
        entry_point: myFnc
        runtime: nodejs16
        project: ${{ secrets.GCP_PROJECT }}

    # Example of using the output
    - id: 'Output function url'
      run: 'curl "${{ steps.deploy-function.outputs.url }}"'
