name: GitHub Actions Gcloud Function Deploy
run-name: ${{ github.actor }} is deploying Gcloud Function 🚀
on:
  push:
    branches:
      - main
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: 'tsc-build'
      name: 'Build Typescript code'
      run: npm run build

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Deploy a Cloud Function
      id: deploy-function
      uses: google-github-actions/deploy-cloud-functions@v0.1.0
      with:
        name: myFnc
        runtime: nodejs16
        project: ${{ secrets.GCP_PROJECT }}
